<?php
/**
 * PageController class file
 *
 * PHP Version 7.2
 *
 * @category Controllers
 * @package  Controllers
 * @author   Hervé Boulangué <h.boulangue@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://blog.local/
 */

namespace Controllers;

use Twig_Environment;
use Twig_Loader_Filesystem;

/**
 * Controller for the rendering of Twig's template
 *
 * @category Controllers
 * @package  Controllers
 * @author   Hervé Boulangué <h.boulangue@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://blog.local/
 */
class Controller
{
    /**
     * @var Twig_Loader_Filesystem
     * Load the template files (contain the directory path)
     */
    protected $loader;

    /**
     * @var Twig_Environment
     * Init the app and load the model
     */
    protected $twig;

    /**
     * Instantiates new Controller.
     */
    public function __construct()
    {
        $this->loader = new Twig_Loader_Filesystem('../Views');
        $this->twig = new Twig_Environment($this->loader, ['cache' => false]);
    }

    /**
     * Render the Twig template.
     *
     * @param string $page
     * Name of the view loaded
     *
     * @param array $args
     * Options for Twig's rendering
     *
     * @return
     * Result generated by Twig
     */
    protected function render(string $page, $args=array()):string
    {
        return $this->twig->render($page, $args);
    }
}
