<?php
/**
 * PageController class file
 *
 * PHP Version 7.2
 *
 * @category Controllers
 * @package  Controllers
 * @author   Hervé Boulangué <h.boulangue@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://blog.local/
 */

namespace Controllers;

use Twig_Environment;
use Twig_Loader_Filesystem;

/**
 * Controller for the rendering of Twig's template
 *
 * @category Controllers
 * @package  Controllers
 * @author   Hervé Boulangué <h.boulangue@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://blog.local/
 */
class Controller
{
    /**
     * Contains the Twig template loader (required for Twig rendering)
     *
     * @var Twig_Loader_Filesystem contains the Twig template loader (required for Twig rendering)
     */
    protected $loader;

    /**
     * Object called the environment, store configuration and extension
     *
     * @var Twig_Environment the Twig Environment (required for Twig rendering)
     */
    protected $twig;

    /**
     * Instantiates new Controller.
     */
    public function __construct()
    {
        $this->loader = new Twig_Loader_Filesystem('../Views');
        $this->twig = new Twig_Environment($this->loader, ['cache' => false]);
    }

    /**
     *  Renders the given twig template with the given arguments and returns the result
     *
     * @param string $page Name of the view loaded
     * @param array $args Options for Twig's rendering
     *
     * @return string the result generated by Twig
     * @throws \Twig_Error_Loader
     * @throws \Twig_Error_Runtime
     * @throws \Twig_Error_Syntax
     */
    protected function render(string $page, $args = array()):string
    {
        $args["user"] = isset($_SESSION["user"]) ? $_SESSION["user"] : null;

        return $this->twig->render($page, $args);
    }

    /**
     * Redirects to login page if the user is not connected, or returns the connected user
     *
     * @return User|void the user if it is connected
     */
    public function redirectToLoginIfNotConnected()
    {
        if(!isset($_SESSION['user'])) {
            header("Location: " . $_SERVER['admin/login.html.twig']);
            exit;
        }
        return $_SESSION['user'];
    }
}
